theme: jekyll-theme-cayman
title: Geospatial Insights from Acorn
description: Insights into local spatial datasets

twitter_username: tyler_acorn
github_username:  tyleracorn
repository: tyleracorn/tyleracorn.github.io
