remote_theme: "mmistakes/minimal-mistakes@4.19.0"
title: "Geospatial Insights: Tyler Acorn"
description: Insights into local spatial datasets

twitter_username: tyler_acorn
github_username:  tyleracorn
repository: tyleracorn/tyleracorn.github.io
google_analytics: UA-127304235-2
